import { AIJob } from '../types.ts';

export const curatedJobs: AIJob[] = [
  {
    id: 'job-1',
    title: 'Frontend Developer Intern',
    company: 'Razorpay',
    location: 'Bengaluru, Karnataka (Hybrid)',
    jobType: 'Internship',
    workMode: 'Hybrid',
    experience: 'Entry Level / Freshers',
    salary: '₹40,000 - ₹50,000 / month',
    datePosted: '1 day ago',
    matchScore: 96,
    matchReason: 'Direct alignment with modern React, TypeScript, and responsive UI fundamentals for junior engineers.',
    description: 'Join our Checkout Experience team to build pixel-perfect, accessible, and fast web experiences used by millions of merchants daily across India.',
    requirements: [
      'Strong proficiency in JavaScript (ES6+), HTML5, and CSS3/Tailwind',
      'Hands-on experience with React.js through projects or previous internships',
      'Understanding of REST APIs and client-side performance',
      'Good communication and eager to learn collaborative Git workflows'
    ],
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Git', 'REST APIs', 'Web Vitals'],
    applyUrl: 'https://razorpay.com/jobs',
    sourcePlatform: 'Razorpay Careers',
    isFeatured: true,
    isVerified: true
  },
  {
    id: 'job-2',
    title: 'Graduate Software Engineer (Trainee)',
    company: 'Cisco',
    location: 'Bengaluru, India',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    experience: '0–1 Years (Batch 2024 / 2025)',
    salary: '₹12,00,000 - ₹15,00,000 / year',
    datePosted: '3 days ago',
    matchScore: 92,
    matchReason: 'Structured graduate hiring program with high mentorship, cloud networking, and Python/Java tracks.',
    description: 'Cisco is seeking passionate university graduates to innovate on cloud networking, cybersecurity solutions, and distributed backend architectures.',
    requirements: [
      'Degree in Computer Science, IT, Electronics or related technical discipline',
      'Solid foundation in Data Structures, Algorithms, and Object-Oriented Design',
      'Working knowledge of Python, Java, or C++',
      'Basic networking concepts (TCP/IP, HTTP, routing fundamentals)'
    ],
    skills: ['Python', 'Java', 'Data Structures', 'Networking', 'Linux', 'Git'],
    applyUrl: 'https://jobs.cisco.com',
    sourcePlatform: 'Cisco University Hiring',
    isFeatured: true,
    isVerified: true
  },
  {
    id: 'job-3',
    title: 'Junior Python & AI Developer',
    company: 'Swiggy',
    location: 'Bengaluru, Karnataka / Remote',
    jobType: 'Full-time',
    workMode: 'Remote',
    experience: 'Entry Level',
    salary: '₹8,00,000 - ₹12,00,000 / year',
    datePosted: '2 days ago',
    matchScore: 90,
    matchReason: 'Great stepping stone for Python builders interested in real-time recommendation engines and FastAPI.',
    description: 'Help develop and maintain microservices and LLM-assisted tools supporting Swiggy delivery logistics and vendor onboarding automation.',
    requirements: [
      'Proficiency in Python (FastAPI, Flask, or Django)',
      'Basic experience with SQL/PostgreSQL databases',
      'Interest in prompt engineering or HuggingFace/Gemini API integrations',
      'Clean coding practices and problem-solving mindset'
    ],
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'AI APIs', 'Git'],
    applyUrl: 'https://careers.swiggy.com',
    sourcePlatform: 'Swiggy Careers',
    isFeatured: false,
    isVerified: true
  },
  {
    id: 'job-4',
    title: 'Product Design (UI/UX) Intern',
    company: 'Zepto',
    location: 'Mumbai, Maharashtra',
    jobType: 'Internship',
    workMode: 'On-site',
    experience: 'Freshers / Students',
    salary: '₹35,000 / month',
    datePosted: 'Just today',
    matchScore: 94,
    matchReason: 'Fast-paced hyper-growth consumer app offering mentorship from senior design leads.',
    description: 'Work side-by-side with our Senior Product Designers to conduct user interviews, prototype micro-interactions, and build components for the Zepto design system.',
    requirements: [
      'Active portfolio showcasing Figma design process, wireframes, and prototypes',
      'Deep curiosity for consumer mobile UX and e-commerce conversion patterns',
      'Strong typography, color balance, and component thinking',
      'Ability to articulate design decisions clearly'
    ],
    skills: ['Figma', 'Prototyping', 'Wireframing', 'User Research', 'Design Systems', 'Micro-interactions'],
    applyUrl: 'https://www.zepto.co.in/careers',
    sourcePlatform: 'Zepto Design',
    isFeatured: true,
    isVerified: true
  },
  {
    id: 'job-5',
    title: 'Associate Data Analyst',
    company: 'Zomato',
    location: 'Gurugram / Delhi NCR',
    jobType: 'Full-time',
    workMode: 'Hybrid',
    experience: '0–1 Years',
    salary: '₹7,50,000 - ₹10,00,000 / year',
    datePosted: '4 days ago',
    matchScore: 89,
    matchReason: 'High-impact business analytics role requiring strong SQL query writing and visualization skills.',
    description: 'Translate operational datasets into actionable insights for restaurant partners and delivery fleet operations. Build automated dashboards and perform A/B test analysis.',
    requirements: [
      'Strong SQL querying skills (joins, window functions, aggregations)',
      'Working knowledge of Python/R (pandas, numpy) or Excel modeling',
      'Familiarity with Tableau, PowerBI, or Metabase',
      'Curious, detail-oriented, and numbers-driven'
    ],
    skills: ['SQL', 'Python', 'PowerBI', 'Tableau', 'Excel', 'A/B Testing'],
    applyUrl: 'https://www.zomato.com/careers',
    sourcePlatform: 'Zomato Talent',
    isFeatured: false,
    isVerified: true
  },
  {
    id: 'job-6',
    title: 'Cloud & DevOps Intern',
    company: 'Infosys Springboard',
    location: 'Pune / Hyderabad (Remote Option)',
    jobType: 'Internship',
    workMode: 'Remote',
    experience: 'Students / Freshers',
    salary: '₹25,000 / month',
    datePosted: '5 days ago',
    matchScore: 88,
    matchReason: 'Ideal learning environment for gaining real AWS, Docker, and CI/CD deployment experience.',
    description: 'Work on enterprise cloud deployment pipelines, containerization using Docker, and automated CI/CD workflows under certified cloud architects.',
    requirements: [
      'Foundational knowledge of Linux operating system commands and shell scripting',
      'Familiarity with Git and GitHub actions',
      'Basic understanding of AWS services (EC2, S3, IAM) or GCP',
      'Enthusiasm for infrastructure as code and automation'
    ],
    skills: ['Linux', 'Docker', 'AWS', 'Bash', 'Git', 'CI/CD'],
    applyUrl: 'https://infyspringboard.onwingspan.com',
    sourcePlatform: 'Infosys Careers',
    isFeatured: false,
    isVerified: true
  },
  {
    id: 'job-7',
    title: 'Cybersecurity Associate Analyst',
    company: 'TCS Cyber Defense',
    location: 'Hyderabad / Chennai',
    jobType: 'Full-time',
    workMode: 'On-site',
    experience: 'Entry Level (0–1 Years)',
    salary: '₹4,50,000 - ₹6,50,000 / year',
    datePosted: '3 days ago',
    matchScore: 87,
    matchReason: 'Comprehensive security operations center (SOC) training with industry certifications sponsorship.',
    description: 'Monitor threat alerts, conduct vulnerability scans, and assist senior analysts in defending enterprise infrastructure against modern cyber incidents.',
    requirements: [
      'Degree in Cyber Security, CS, or relevant security certifications (CompTIA Security+, CEH)',
      'Understanding of network security protocols, firewalls, and SIEM tools',
      'Familiarity with common vulnerabilities (OWASP Top 10)',
      'Analytical thinking and proactive threat-hunting mindset'
    ],
    skills: ['Cybersecurity', 'Network Security', 'SIEM', 'Linux', 'Vulnerability Assessment', 'OWASP'],
    applyUrl: 'https://www.tcs.com/careers',
    sourcePlatform: 'TCS NextStep',
    isFeatured: false,
    isVerified: true
  },
  {
    id: 'job-8',
    title: 'Full Stack Web Developer Intern',
    company: 'Zerodha',
    location: 'Bengaluru, Karnataka',
    jobType: 'Internship',
    workMode: 'Hybrid',
    experience: 'Freshers',
    salary: '₹45,000 / month',
    datePosted: '2 days ago',
    matchScore: 95,
    matchReason: 'Top engineering culture emphasizing clean open-source tech (Go, Vue/React, PostgreSQL).',
    description: 'Contribute to lightweight, robust trading tools and educational financial platforms used by over 10 million active retail investors in India.',
    requirements: [
      'Self-driven coder with demonstrated personal open-source projects on GitHub',
      'Good command of Go, Python, or TypeScript',
      'Deep respect for clean code, minimal bloat, and fast response times',
      'Strong grasping of web protocols and relational databases'
    ],
    skills: ['TypeScript', 'Go', 'React', 'PostgreSQL', 'Redis', 'Open Source'],
    applyUrl: 'https://zerodha.tech',
    sourcePlatform: 'Zerodha Tech',
    isFeatured: true,
    isVerified: true
  }
];
